// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SekaiPlatform.Database;

#nullable disable

namespace SekaiPlatform.Database.Migrations
{
    [DbContext(typeof(SekaiPlatformDbContext))]
    [Migration("20260505142546_AddTranslationVersionMetadata")]
    partial class AddTranslationVersionMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SekaiPlatform.Database.Story", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scenario_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("story_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StoryType", "ScenarioId")
                        .IsUnique();

                    b.ToTable("stories", null, t =>
                        {
                            t.HasCheckConstraint("CK_stories_story_type", "story_type IN ('event_story', 'card_story', 'main_story', 'area_talk', 'special_story')");
                        });
                });

            modelBuilder.Entity("SekaiPlatform.Database.StoryGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DisplayNo")
                        .HasColumnType("integer")
                        .HasColumnName("display_no");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("external_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("StoryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("story_type");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StoryType", "ExternalType", "ExternalId")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("StoryType", "ExternalType", "ExternalId"), false);

                    b.ToTable("story_groups", null, t =>
                        {
                            t.HasCheckConstraint("CK_story_groups_story_type", "story_type IN ('event_story', 'card_story', 'main_story', 'area_talk', 'special_story')");
                        });
                });

            modelBuilder.Entity("SekaiPlatform.Database.StorySourceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("line_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Speaker")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("speaker");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("story_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StoryId", "LineNo")
                        .IsUnique();

                    b.ToTable("story_source_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_story_source_lines_line_type", "line_type IN ('dialogue', 'scene', 'upper_scene', 'choice', 'separator')");
                        });
                });

            modelBuilder.Entity("SekaiPlatform.Database.SyncJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("job_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("sync_jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_sync_jobs_status", "status IN ('pending', 'running', 'succeeded', 'failed')");

                            t.HasCheckConstraint("CK_sync_jobs_trigger_type", "trigger_type IN ('manual', 'scheduled')");
                        });
                });

            modelBuilder.Entity("SekaiPlatform.Database.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SekaiPlatform.Database.TranslationLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<long>("SourceLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_line_id");

                    b.Property<string>("Speaker")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("speaker");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("story_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceLineId", "StoryId");

                    b.HasIndex("VersionId", "LineNo")
                        .IsUnique();

                    b.HasIndex("VersionId", "SourceLineId")
                        .IsUnique();

                    b.HasIndex("VersionId", "StoryId");

                    b.ToTable("translation_lines", (string)null);
                });

            modelBuilder.Entity("SekaiPlatform.Database.TranslationVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<long>("StoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("story_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StoryId");

                    b.HasIndex("TenantId", "CreatedBy");

                    b.HasIndex("TenantId", "StoryId", "VersionNo")
                        .IsUnique();

                    b.ToTable("translation_versions", (string)null);
                });

            modelBuilder.Entity("SekaiPlatform.Database.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("QqId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("qq_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("QqId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SekaiPlatform.Database.UserOAuth", b =>
                {
                    b.Property<string>("OAuthType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("oauth_type");

                    b.Property<string>("OAuthId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("oauth_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("OAuthType", "OAuthId");

                    b.HasIndex("UserId");

                    b.ToTable("user_oauthes", (string)null);
                });

            modelBuilder.Entity("SekaiPlatform.Database.UserTenant", b =>
                {
                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_tenants_role", "role IN ('normal', 'admin', 'super_admin')");

                            t.HasCheckConstraint("CK_user_tenants_status", "status IN ('active', 'disabled', 'deleted')");
                        });
                });

            modelBuilder.Entity("SekaiPlatform.Database.Story", b =>
                {
                    b.HasOne("SekaiPlatform.Database.StoryGroup", "Group")
                        .WithMany("Stories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SekaiPlatform.Database.StorySourceLine", b =>
                {
                    b.HasOne("SekaiPlatform.Database.Story", "Story")
                        .WithMany("SourceLines")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("SekaiPlatform.Database.TranslationLine", b =>
                {
                    b.HasOne("SekaiPlatform.Database.StorySourceLine", "SourceLine")
                        .WithMany("TranslationLines")
                        .HasForeignKey("SourceLineId", "StoryId")
                        .HasPrincipalKey("Id", "StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SekaiPlatform.Database.TranslationVersion", "Version")
                        .WithMany("Lines")
                        .HasForeignKey("VersionId", "StoryId")
                        .HasPrincipalKey("Id", "StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceLine");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("SekaiPlatform.Database.TranslationVersion", b =>
                {
                    b.HasOne("SekaiPlatform.Database.User", "Creator")
                        .WithMany("CreatedTranslationVersions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SekaiPlatform.Database.Story", "Story")
                        .WithMany("TranslationVersions")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SekaiPlatform.Database.Tenant", "Tenant")
                        .WithMany("TranslationVersions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SekaiPlatform.Database.UserTenant", "CreatorMembership")
                        .WithMany()
                        .HasForeignKey("TenantId", "CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("CreatorMembership");

                    b.Navigation("Story");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SekaiPlatform.Database.UserOAuth", b =>
                {
                    b.HasOne("SekaiPlatform.Database.User", "User")
                        .WithMany("UserOAuths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SekaiPlatform.Database.UserTenant", b =>
                {
                    b.HasOne("SekaiPlatform.Database.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SekaiPlatform.Database.User", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SekaiPlatform.Database.Story", b =>
                {
                    b.Navigation("SourceLines");

                    b.Navigation("TranslationVersions");
                });

            modelBuilder.Entity("SekaiPlatform.Database.StoryGroup", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("SekaiPlatform.Database.StorySourceLine", b =>
                {
                    b.Navigation("TranslationLines");
                });

            modelBuilder.Entity("SekaiPlatform.Database.Tenant", b =>
                {
                    b.Navigation("TranslationVersions");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("SekaiPlatform.Database.TranslationVersion", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SekaiPlatform.Database.User", b =>
                {
                    b.Navigation("CreatedTranslationVersions");

                    b.Navigation("UserOAuths");

                    b.Navigation("UserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
